name: Deployments Updater

on:
  workflow_run:
    workflows: ["Build all Images"]  # Nome do outro workflow que será monitorado
    types:
      - completed  
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout deployments repository
        uses: actions/checkout@v3
        with:
          repository: endvrtech/deployments
          path: deployments
          token: ${{ secrets.DEPLOYMENT_PAT }}
          ref: refs/heads/main

      - name: Update deployments repository
        run: |
          cd deployments
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git pull origin main --ff-only
          git add --all
          git commit -m "Update image tag to ${{ needs.build-applications.outputs.app }}:${{ env.ENVIRONMENT }}"
          git push
