name: Test Workflow

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      repository:
        required: true
        type: string
      production_branch:
        required: false
        type: string
        default: "main"
      docker_file:
        required: false
        default: "Dockerfile"
        type: string
      docker_context:
        required: false
        default: "."
        type: string
      docker_args:
        required: false
        default: ""
        type: string
      dockerhub_username:
        required: false
        default: "endvrteam"
        type: string
    secrets:
      deployment_pat:
        required: true
      dockerhub_pwd:
        required: true
      slack_bot_token:
        required: true
      slack_channel:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v6

      - name: Define mode based on branch
        id: set_mode
        run: |
          branch_name="${{ steps.branch.outputs.current_branch }}"
          echo "MODEBRANCH=$branch_name" >> $GITHUB_ENV

      - name: Docker - Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker - Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.dockerhub_pwd }}

      - name: Docker - Build image and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.docker_file }}
          push: true
          build-args: |
            mode=${{ env.MODEBRANCH }}
          tags: ${{ inputs.repository }}:${{ github.sha }}

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: "Failure in the Build and Deploy process for the image ${{ inputs.app }}. Error in the Build step.\n\nSee more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          path: main

      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v6

      - name: Define environment for deploy
        run: |
          if [ "${{ steps.branch.outputs.current_branch }}" == "${{ inputs.production_branch }}" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ steps.branch.outputs.current_branch }}" >> $GITHUB_ENV
          fi

      - name: Prepare deployments repository
        uses: actions/checkout@v3
        with:
          repository: endvrtech/deployments
          path: deployments
          token: ${{ secrets.deployment_pat }}
          ref: refs/heads/main

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag
        run: |
          cd deployments/k8s/apps/${{ inputs.app }}/overlays/${{ env.ENVIRONMENT }}
          kustomize edit set image appimage=${{ inputs.repository }}:${{ github.sha }}

      - name: Update deployments repository
        run: |
          cd deployments
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git pull origin main --ff-only
          git add --all
          git commit -m "Update image tag to ${{ inputs.app }}:${{ env.ENVIRONMENT }}"
          git push

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: "Failure in the Deploy process for the ${{ env.ENVIRONMENT }} environment of the application ${{ inputs.app }}. Error in the Deploy step.\n\nSee more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
