name: Verificar ou Atualizar Arquivo

on:
  push:
    branches:
      - main

jobs:
  verificar_atualizar_arquivo:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Verificar ou atualizar o arquivo
      run: |
        FILE="pipeteste"
        DEFAULT_VALUE="0123456789"
        
        # Verifica se o arquivo existe
        if [ -f "$FILE" ]; then
          echo "O arquivo $FILE existe."
          
          # Lê o conteúdo do arquivo
          CONTENT=$(cat $FILE)
          
          if [ "$CONTENT" = "$DEFAULT_VALUE" ]; then
            echo "O valor do arquivo é igual ao padrão ($DEFAULT_VALUE)."
            
            # Gera um número aleatório e atualiza o arquivo
            RANDOM_VALUE=$(( RANDOM % 100000 ))
            echo $RANDOM_VALUE > $FILE
            echo "Valor atualizado para um número aleatório: $RANDOM_VALUE"
          else
            echo "O valor do arquivo é diferente do padrão ($DEFAULT_VALUE)."
            
            # Atualiza o arquivo para o valor padrão
            echo $DEFAULT_VALUE > $FILE
            echo "Valor atualizado para o padrão: $DEFAULT_VALUE"
          fi
        else
          echo "O arquivo $FILE não existe. Criando com o valor padrão ($DEFAULT_VALUE)."
          
          # Cria o arquivo com o valor padrão
          echo $DEFAULT_VALUE > $FILE
        fi

    - name: Configurar Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commitar e fazer push
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add pipeteste
        git commit -m "Atualizar arquivo pipeteste"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/reginaabarbara/pipelines.git main 
