name: Verificar, Atualizar e Enviar para Telegram

on:
  push:
    branches:
      - main

jobs:
  verificar_atualizar_arquivo:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Verificar ou atualizar o arquivo
      id: verificar_arquivo
      run: |
        FILE="pipeteste"
        DEFAULT_VALUE="0123456789"
        
        if [ -f "$FILE" ]; then
          CONTENT=$(cat $FILE)
          if [ "$CONTENT" = "$DEFAULT_VALUE" ]; then
            RANDOM_VALUE=$(( RANDOM % 100000 ))
            echo $RANDOM_VALUE > $FILE
            CONTENT=$RANDOM_VALUE
          else
            echo $DEFAULT_VALUE > $FILE
            CONTENT=$DEFAULT_VALUE
          fi
        else
          echo $DEFAULT_VALUE > $FILE
          CONTENT=$DEFAULT_VALUE
        fi

        echo "content=$CONTENT" >> $GITHUB_ENV

    - name: Configurar Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commitar e fazer push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add pipeteste
        git commit -m "Atualizar arquivo pipeteste"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/reginaabarbara/pipelines.git main

    - name: Enviar para Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        FILE_CONTENT: ${{ env.content }}
      run: |
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="O conteúdo do arquivo pipeteste é: $FILE_CONTENT"
