name: Criar e Enviar Arquivo

on:
  push:
    branches:
      - main

jobs:
  criar_arquivo_e_enviar:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Criar o arquivo
      run: echo "0123456789" > pipeteste

    - name: Configurar Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commitar e fazer push
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add pipeteste
        git commit -m "Adicionar arquivo pipeteste"
        git push https://$GH_PAT@github.com/reginaabarbara/pipelines.git main
